kind:  ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: keycloak
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
#    - git:
#        repoURL: https://github.com/CottonCandy01/keycloak.git
#        revision: helm
#        directories:
#          - path: keycloak
#          - path: operator
    - list:
        elements:
          - name: keycloak
            url: https://github.com/bitnami/charts.git
            helm: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/CottonCandy01/keycloak.git
        targetRevision: helm
        path: '{{.path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true