kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
   name: keycloak-operator
   namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/kbumsik/keycloak-kubernetes.git
    targetRevision: HEAD
    path: charts/keycloak-operator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

